// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8zI7J-STVMzWiYlc0TfEPAimewI4MNmg',
    appId: '1:218687130050:web:ed3bf4dcdbb5070a3a2e5b',
    messagingSenderId: '218687130050',
    projectId: 'al-dhile-208',
    authDomain: 'al-dhile-208.firebaseapp.com',
    storageBucket: 'al-dhile-208.appspot.com',
    measurementId: 'G-QRSHTBENX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVl79I2tRmiyM19ZY_akeHbQWrsN9U3To',
    appId: '1:218687130050:android:037667f67a953ba83a2e5b',
    messagingSenderId: '218687130050',
    projectId: 'al-dhile-208',
    storageBucket: 'al-dhile-208.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALrUVtpLiaFd_XwZvspekgogCUgWcIe_I',
    appId: '1:218687130050:ios:e9f8bffb91e3fe133a2e5b',
    messagingSenderId: '218687130050',
    projectId: 'al-dhile-208',
    storageBucket: 'al-dhile-208.appspot.com',
    iosBundleId: 'com.Maxart.Dhile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALrUVtpLiaFd_XwZvspekgogCUgWcIe_I',
    appId: '1:218687130050:ios:0d88e8633cddc6d13a2e5b',
    messagingSenderId: '218687130050',
    projectId: 'al-dhile-208',
    storageBucket: 'al-dhile-208.appspot.com',
    iosBundleId: 'dhile.ae.dhile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8zI7J-STVMzWiYlc0TfEPAimewI4MNmg',
    appId: '1:218687130050:web:6a088e9842eec5c13a2e5b',
    messagingSenderId: '218687130050',
    projectId: 'al-dhile-208',
    authDomain: 'al-dhile-208.firebaseapp.com',
    storageBucket: 'al-dhile-208.appspot.com',
  );

}